---
title: 'Progress Report'
author: "Eitan Tuchin"
date: "2025-04-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(rvest)
library(readr)
library(tidyverse)
library(Lahman)
library(stringr)
library(stringi)

url <- "https://www.baseball-reference.com/awards/hof_2025.shtml"
html <- read_html(url)
tables <- html_table(html)

head(tables[[1]])
data <- tables[[1]]
actual_col_names <- data[1, ]

colnames(data) <- actual_col_names
data <- data[-1, ]
head(data)
names(data) <- make.unique(names(data))

data <- data %>%
  mutate(
    across(
      c(
        Votes, `%vote`, HOFm, HOFs, Yrs, WAR, WAR7, JAWS, Jpos,
        G, AB, R, H, HR, RBI, SB, BB, BA, OBP, SLG, OPS, `OPS+`,
        W, L, ERA, `ERA+`, WHIP, 
        G.1, GS, SV, IP, H.1, HR.1, BB.1, SO
      ),
      ~ as.numeric(parse_number(.))
    )
  )

data <- data %>%
  mutate(`First Lastname` = str_trim(`Name`))

data$`First Lastname` <- str_remove(data$`First Lastname`, "^[A-Z]-")
data$`First Lastname` <- stri_trans_general(data$`First Lastname`, "Latin-ASCII")

People_needed_info <- People %>%
  mutate(
    `First Lastname` = paste(str_replace(nameFirst, "\\. ", "."), nameLast)
  ) %>%
  select(playerID, `First Lastname`)

data <- data %>%
  left_join(People_needed_info, by = 'First Lastname')

data_modified <- data %>%
  mutate(
    yearID = 2025,
    votedBy = "BBWAA",
    ballots = max(Votes, na.rm = TRUE), 
    needed = round(0.75 * ballots),
    votes = Votes,
    inducted = if_else(votes >= needed, "Y", "N"),
    category = "player",
    needed_note = NA
  ) %>%
  select(colnames(HallOfFame))

head(data_modified)

write.csv(data_modified, file = "eitantuchin_hof_2025_clean.csv", row.names = FALSE)

data(HallOfFame, package = "Lahman")

combined_hof <- rbind(HallOfFame, data_modified)

head(combined_hof, 3)
tail(combined_hof, 3)

combined_hof %>%
  ggplot(aes(x = yearID, fill = inducted)) +
  geom_bar() +
  xlim(c(1936, 2025)) +
  labs(title = "Hall of Fame Voting by Year", x = "Year", y = "Count", fill = "Inducted")

write_csv(combined_hof, file = "HallOfFame.csv")
```